#
# Module manifest for module 'Initialize-ASTRuleGenerator'
#
# Generated by: lucas.cueff[at]lucas-cueff.com
#
# Generated on: 08/12/2021
#

@{

    # Script module or binary module file associated with this manifest.
    RootModule = 'Initialize-ASTRuleGenerator.psm1'
    
    # Version number of this module.
    ModuleVersion = '0.5'
    
    # ID used to uniquely identify this module
    GUID = '1b00b851-b466-4a87-a99f-071d0c00f84a'
    
    # Author of this module
    Author = 'Lucas Cueff'
    
    # Company or vendor of this module
    CompanyName = 'lucas-cueff.com'
    
    # Copyright statement for this module
    Copyright = '(c) 2021 lucas-cueff.com Distributed under Artistic Licence 2.0 (https://opensource.org/licenses/artistic-license-2.0).'
    
    # Description of the functionality provided by this module
    Description = 'This module contains a function used to generate automatically PSScriptAnalyzer rules based on a configuration JSON file Initialize-ASTRuleGenerator.json.'
    
    # Minimum version of the Windows PowerShell engine required by this module
    PowerShellVersion = '3.0'
    
    # Name of the Windows PowerShell host required by this module
    # PowerShellHostName = ''
    
    # Minimum version of the Windows PowerShell host required by this module
    # PowerShellHostVersion = ''
    
    # Minimum version of Microsoft .NET Framework required by this module
    # DotNetFrameworkVersion = ''
    
    # Minimum version of the common language runtime (CLR) required by this module
    CLRVersion = '4.0'
    
    # Processor architecture (None, X86, Amd64) required by this module
    # ProcessorArchitecture = ''
    
    # Modules that must be imported into the global environment prior to importing this module
    # RequiredModules = @()
    
    # Assemblies that must be loaded prior to importing this module
    # RequiredAssemblies = @()
    
    # Script files (.ps1) that are run in the caller's environment prior to importing this module.
    # ScriptsToProcess = @()
    
    # Type files (.ps1xml) to be loaded when importing this module
    # TypesToProcess = @()
    
    # Format files (.ps1xml) to be loaded when importing this module
    # FormatsToProcess = @()
    
    # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
    # NestedModules = @()
    
    # Functions to export from this module
    FunctionsToExport = 'Measure-CustomASTRule'
    
    # Cmdlets to export from this module
    CmdletsToExport = '*'
    
    # Variables to export from this module
    VariablesToExport = '*'
    
    # Aliases to export from this module
    AliasesToExport = '*'
    
    # List of all modules packaged with this module
    # ModuleList = @()
    
    # List of all files packaged with this module
    FileList = @('Initialize-ASTRuleGenerator.psm1','Initialize-ASTRuleGenerator.psd1','Initialize-ASTRuleGenerator.json')
    
    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData = @{
    
        PSData = @{
    
            # Tags applied to this module. These help with module discovery in online galleries.
            Tags = @('AST','AbstractSyntaxTree','PowerShell','ScriptAnalyzer','PSScriptAnalyzer','CustomSecurityAnalyzer')
    
            # A URL to the license for this module.
            LicenseUri = 'https://opensource.org/licenses/artistic-license-2.0'
    
            # A URL to the main website for this project.
            ProjectUri = 'https://github.com/MS-LUF/Initialize-ASTRuleGenerator'
    
            # A URL to an icon representing this module.
            IconUri = 'http://www.lucas-cueff.com/files/gallery.png'
    
            # ReleaseNotes of this module
            ReleaseNotes = 'First release of Initialize-ASTRuleGenerator : generate automatically PSScriptAnalyzer rules based on a configuration JSON file Initialize-ASTRuleGenerator.json.'
    
        } # End of PSData hashtable
    
    } # End of PrivateData hashtable
    
    # HelpInfo URI of this module
    # HelpInfoURI = ''
    
    # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
    # DefaultCommandPrefix = ''
    
    }